### ISSUE TITLE
Error on node start in stellar testnet when following quick start

### ISSUE THREAD

**Issue by carlosdimatteo** [subquery/subql-stellar#52] opened 2024-03-11 14:44 UTC
### Prerequisites

* [X] Are you running the latest version(s)?
 @subql/cli/4.4.1 darwin-arm64 node-v20.11.0
* [X] Have you searched the [documentation for your issue](https://academy.subquery.network/)?
yes, have'nt found anything related
* [X] Did you search for an existing issue or pull request?
yes, only thing i found was this PR, but can't decifer its relation to my issue 

### Details

These details can help to reproduce the environment the issue is occurring

**Local Environment:** 
 @subql/cli/4.4.1 darwin-arm64 node-v20.11.0 
 
**Network Details:**

  Stellar Testnet 
  Block heights : 512152 & 228206 & 401077, any really 

  endpoint: ["https://horizon-testnet.stellar.org"]
   sorobanEndpoint: "https://soroban-testnet.stellar.org"

### Steps to Reproduce

1. [First Step]

Follow the starting example from the subquery documentation : https://academy.subquery.network/quickstart/quickstart_chains/stellar.html
once you get to the deployment and running part it throws an error no matter the startBlock you input 

**Example project:** [A link to a minimal example that can reproduce the issue]
https://academy.subquery.network/quickstart/quickstart_chains/stellar.html
**Expected behavior:** [What you expected to happen]
Example running in docker as expected, no errors
**Actual behavior:** [What actually happened]
```
subquery-node-1   | 2024-03-08T22:19:53.811Z <subql-node> ERROR Node failed to start Error: Value at height 301081 was undefined
```

here's the run block of the command 
https://app.warp.dev/block/2Ko4budYDz9YUTHhu0MMoK

**Comment by stwiname** [comment] 2024-03-12 00:51
Hi @carlosdimatteo i have been unable to reproduce the same error. I did make a couple of unrelated fixes to the starter projects. Are you able to please try again with an updated starter and let me know if the issue persists.

**Comment by carlosdimatteo** [comment] 2024-03-12 14:46
hey @stwiname thanks! 
I deleted the repo where i was following the starter guide and cloned  the stellar testnet starter and pulled, still encountering the following  errors: 

```
ERROR failed to index block at height 512152  Error: The requested events for ledger number 512152 is not available on the current soroban node.
subquery-node-1   |                 This is because you're trying to access a ledger that is older than the oldest ledger stored in this node.
subquery-node-1   |                 To resolve this issue, you can either:
subquery-node-1   |                 1. Increase the start ledger to a more recent one, or
subquery-node-1   |                 2. Connect to a different node that might have a longer history of ledgers.
```

changed the startBlock to `573352`

and it throws : 

```
ERROR Failed to index block 573354: VMError: Cannot find module 'stream'
subquery-node-1   |     at CustomResolver.resolveFull (/node_modules/vm2/lib/resolver.js:126:9)
subquery-node-1   |     at CustomResolver.resolveFull (/node_modules/vm2/lib/resolver.js:316:16)
subquery-node-1   |     at CustomResolver.resolve (/node_modules/vm2/lib/resolver.js:121:15)
subquery-node-1   |     at resolve (/node_modules/vm2/lib/nodevm.js:317:21)
subquery-node-1   |     at VM2 Wrapper.apply (/node_modules/vm2/lib/bridge.js:485:11)
subquery-node-1   |     at requireImpl (/node_modules/vm2/lib/setup-node-sandbox.js:90:19)
subquery-node-1   |     at require (/node_modules/vm2/lib/setup-node-sandbox.js:171:10)
subquery-node-1   |     at 2203 (webpack://soroban-testnet-starter/external node-commonjs "stream":1:17)
subquery-node-1   |     at n (webpack://soroban-testnet-starter/webpack/bootstrap:19:31)
subquery-node-1   |     at 801 (webpack://soroban-testnet-starter/node_modules/combined-stream/lib/combined_stream.js:2:13) VMError: Cannot find module 'stream'
```


I tried using both npm and yarn , hit the same issue , if you have a branch or a reference to your project setup that i can use to reproduce your working environment that would be useful, let me know

**Comment by stwiname** [comment] 2024-03-13 00:48
The first issue is because of a pruned node and the second one should be resolved with the `unsafe` flag

**Closed** 2024-09-03 22:53 UTC
Labels: bug
